### ISSUE TITLE
Updating v4.3.0

### ISSUE THREAD

**Issue by ligrevx** [AdoPiSoft/Releases#1]
When updating to `v4.3.0` the default db set to `sqlite`. Users need to manually input to `System` > `Security` > `Database Connection`; and select their `Database Type`.

**Comment by ligrevx** [comment]
Update:

This issue was only occured in vbox machine using `adopisoft-4.2.1-amd64-node-v12.18.3.deb`.

Playing around today on `rpi 4` using the `v4.2.1` and updated to `v4.3.0` works flawlessly.

**Comment by alenteria** [comment]
Just use the deb file version provided in the wiki guide and just upgrade to latest version in the admin.
