### ISSUE TITLE
can the orange pi pc img be used on the orange pi plus?

### ISSUE THREAD

**Issue by madorax251** [AdoPiSoft/Releases#10]
This type of orange pi plus I use https://www.armbian.com/orange-pi-plus/ please help

**Comment by madorax251** [comment]
https://www.adopisoft.com/download_options?board=opi1_plus  I've tried both and neither of them
can work in
my orange pi plus

**Comment by alenteria** [comment]
this board is untested

**Comment by alenteria** [comment]
let’s continue on #9
