### ISSUE TITLE
block wifi sharing hotspot mobile phone & can't setting ado arm64 manual instalation

### ISSUE THREAD

**Issue by arnet1** [AdoPiSoft/Releases#16]
-please add option for block sharing hotspot mobile devices like mikrotik Change TTL1
-can't create admin wen firs time setup wizard adopisoft V5.1.1 arm64

**Comment by alenteria** [comment]
This is already implemented. See network->interface settings then LAN/captive-portal interface. There's a a field in there labeled "Hop". Set it to *1* to disable wifi sharing.

**Comment by arnet1** [comment]
i have set to 1, but stile working sharing hotspot, i'm using ado ubuntu server amd64

**Comment by arnet1** [comment]
![Uploading IMG_20220805_135345.jpg…]()

**Comment by alenteria** [comment]
> i have set to 1, but stile working sharing hotspot, i'm using ado5.1.1 ubuntu server amd64

Please send screenshot

**Comment by arnet1** [comment]
tq solved
