### ISSUE TITLE
system error after 36h

### ISSUE THREAD

**Issue by ligrevx** [AdoPiSoft/Releases#2]
After 36 hours uptime.

See attached.

web & /opt/adopisoft/system.log

![6C8CFAA3-CEAD-414D-A62F-E5678E862D69](https://user-images.githubusercontent.com/1475200/113300891-fdc21380-9330-11eb-8fbe-16df569b31b9.png)
![D6CB66FE-C2B4-4A1E-9D5F-AD1DEAE74D28](https://user-images.githubusercontent.com/1475200/113300877-fac72300-9330-11eb-9908-8bd1d7f58322.png)

**Comment by ligrevx** [comment]
Twice na ni nako na encounter. Evening time gihapon, peak hours nako.
![065304DE-EA78-4C6B-A4E6-645E6F0B05A5](https://user-images.githubusercontent.com/1475200/113302139-580fa400-9332-11eb-8023-30ab7a86f304.png)

**Comment by ligrevx** [comment]
So far, akong longest uptime is 3 days pa.

**Comment by ligrevx** [comment]
[system.log](https://github.com/AdoPiSoft/Releases/files/6243952/system.log)

**Comment by alenteria** [comment]
base sa error
nag hangup ang database connection.
probably sa sd card na gamit nag freeze habang tumatagal na gamit

**Comment by ligrevx** [comment]
rpi 3b+. try nako replace sd card puhon. salamat

**Comment by alenteria** [comment]
will close this issue now
Please reopen if the problem persist
