### ISSUE TITLE
?

### ISSUE THREAD

**Issue by ligrevx** [AdoPiSoft/Releases#3]
not sure. pls confirm. v4.3.0

see attached img:
![916D3C11-EE98-48B7-82B3-A60289F29928](https://user-images.githubusercontent.com/1475200/116242503-8c8f4800-a798-11eb-9288-edf955a05862.png)

**Comment by alenteria** [comment]
modem dashboard to sir?

**Comment by ligrevx** [comment]
> modem dashboard to sir?

yes sir. naa siya sa port 3 unya mo leak man ang mac addresses w/ 0.0.0.0 ip addr. maka verify ba ka sa imo end sir?

**Comment by alenteria** [comment]
> > modem dashboard to sir?
> 
> yes sir. naa siya sa port 3 unya mo leak man ang mac addresses w/ 0.0.0.0 ip addr. maka verify ba ka sa imo end sir?

This is caused by VLAN which is enabled by default if Business version image is used. If hindi VLAN ang setup, remove the VLAN config sa admin:
 1. network->Interfaces br0 uncheck "eth0.22"
 2. network-> 802.1q (VLAN) Remove or delete vlan

**Comment by ligrevx** [comment]
> > > modem dashboard to sir?
> > 
> > 
> > yes sir. naa siya sa port 3 unya mo leak man ang mac addresses w/ 0.0.0.0 ip addr. maka verify ba ka sa imo end sir?
> 
> This is caused by VLAN which is enabled by default if Business version image is used. If hindi VLAN ang setup, remove the VLAN config sa admin:
> 
> 1. network->Interfaces br0 uncheck "eth0.22"
> 2. network-> 802.1q (VLAN) Remove or delete vlan

ok, thank you @alenteria
