### ISSUE TITLE
Single MariaDB server for multiple adopi

### ISSUE THREAD

**Issue by nakpilse** [AdoPiSoft/Releases#35]
Will it work if the scenario is this, let say 10 individual adopi vendo then all of them are connected to a single MariaDB server.

1). Will it work when the client transfers its connection from adopi vendo to another adopi vendo?
2). Will it be centralized?
3). Will it work in VLAN configuration. (different vlan per vendo)

**Comment by alenteria** [comment]
We recommend you use postgresql instead. 
Yes they will all centralized given you are using same cloud based database server and with the same centralized server token in the ado admin db setting.
And any network setting will work.
