### ISSUE TITLE
Prevent clients from accessing specific IP.

### ISSUE THREAD

**Issue by ligrevx** [AdoPiSoft/Releases#4]
`Firewall` tab.
A built-in or maybe a plugin to enable/disable, select specific/all from accessing specific IP e.g. IP cameras, NVRs, routers, etc.

**Comment by ligrevx** [comment]
nag try ko karun block tanan clients from accessing main router `192.168.254.254`, pero mao ni problema nako kay di na nako makita ang network traffic ug active clients.

`iptables -I FORWARD 3 -s 10.0.0.0/20 -d 191.168.254.254 -p tcp —dport 80 -j DROP`

![54433AF5-54D3-4A6E-893D-8AE9D59F35D3](https://user-images.githubusercontent.com/1475200/116886002-23f21080-ac5b-11eb-8379-2be97b6bcbea.png)
![B4A84C74-BB72-42EA-B406-D68D3B96AF49](https://user-images.githubusercontent.com/1475200/116886022-28b6c480-ac5b-11eb-90d4-08d90d8e4e71.png)

![A48E0E81-E394-49A8-8D5C-B0CAB3FDE30D](https://user-images.githubusercontent.com/1475200/116886015-27859780-ac5b-11eb-9b96-8c8d5b080884.png)

**Comment by alenteria** [comment]
You can use this setting sa captive portal interface

![image](https://user-images.githubusercontent.com/2783217/116949857-fb4b3480-acb5-11eb-9811-69f177a923d7.png)

**Comment by alenteria** [comment]
You should not manually alter iptable forward rules, it will conflict with the tracking of the existing captive portal rules

**Comment by ligrevx** [comment]
> You can use this setting sa captive portal interface
> 
> ![image](https://user-images.githubusercontent.com/2783217/116949857-fb4b3480-acb5-11eb-9811-69f177a923d7.png)

ah ok, salamat. naa na man diay ni nga option. wala lang ko kabantay.
