### ISSUE TITLE
Occuring error from users

### ISSUE THREAD

**Issue by kryptoscode** [AdoPiSoft/Releases#6]
![system_log_error](https://user-images.githubusercontent.com/84788284/119513409-c5760900-bda6-11eb-922c-b9185266c02a.png)
![adoerror](https://user-images.githubusercontent.com/84788284/119513528-e2aad780-bda6-11eb-981f-bcaff14124fc.jpg)

Just want to raise this issue seems for a couple of days some of the users have encountered this issue. They cant connect to the portal and the error appears as per the attached picture. 

Restarting the server temporarily fixes the issue but will occur again in a few days.

My Hardware Specs:
Intel Nuc i3
4GB ram
m.2 120GB SSD

**Comment by kryptoscode** [comment]
I may add this error before I have shutdown the server.
![system_log_error2](https://user-images.githubusercontent.com/84788284/119515049-1c301280-bda8-11eb-86c5-5f2f7f0d2d05.png)

**Comment by alenteria** [comment]
These are the possible causes:
- unstable USBLan adapter
  * possible fix, double check LAN adapter. Replace or use VLAN setup if possible
  
- using lower version with PPPOE plugin installed
   * Make sure you are using the latest version for ado software and pppoe plugin

**Comment by kryptoscode** [comment]
Already remove my usb to lan adaptor as previously causes another error before. Currently on vlan using the built-in lan.  Using also version 1.0.3 PPoe plugin. Or maybe Ill uninstall PPPOe plugin for the moment since i don't use it for the moment? I remember it linking this to my usb lan before. Could it be sir that this relates to my issue?

**Comment by kryptoscode** [comment]
Using the latest sir, 4.3.0 on Ubuntu 20.04.2 LTS

**Comment by alenteria** [comment]
> Using the latest sir, 4.3.0 on Ubuntu 20.04.2 LTS

I see, ubuntu 18.04 is more stable and tested for ado. If possible, reinstall OS and use ubuntu 18

**Comment by kryptoscode** [comment]
ah ok boss, if it will error again ill probably downgrade to Ubuntu 18. Thanks!
